name: Actions Workflow

on: 
  #repository_dispatch:
    #types: ["build"]
  #schedule:
    #- cron: "0/5 * * * *"
    #- cron: "0/6 * * * *"
  push:
    branches:
      - master
      - 'feature/*' # doesn't match feature/feat/a
      - 'feature/**' # matches feature/feat/a
      - '!feature/featC' # ignores this branch. You have to put it at last on the list
    tags:
      - v1.*
    # you cannot have both tags and tags-ignore
    #tags-ignore:

    # you cannot have both paths and paths-ignore
    #paths-ignore:
    paths:
      - '**.js' # only run this workflow if we change some *.js file
      - '!filename.js'
    # you cannot have both branches and branches_ignore
    #branches-ignore:
    #  - master
  #pull_request:
  #  types: [closed, assigned, opened, reopened]

#actions can either receive inputs or retrieve outputs

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1 #checks out to the commit that triggered the workflow
      - name: List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          # echo "${{ github.token }}"

      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1 #this a repository in github
        with:
          who-to-greet: Paulo
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"