name: Shell Commands 

on: [push]

jobs:
  shell-commands:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script 
        run: |
          echo "start script"
          node -v 
          npm -v
          echo "end script!"
      - name: python Command
        run: |
          import platform
          print
          (platform.processor())
        shell: python
  windows-commands:
    runs-on: windows-latest
    needs: ["shell-commands"]
    steps:
      - name: Directory Powershell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash #you can run bash in windows. It is a supported shell